import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"

export default function Home() {
  return (
    <div className="mx-auto "  >
      <Head>
        <title>noru ✨ web dev ✨ student </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative" >
        <Header />
        <div className="absolute right-20" >
          <div className="animate-mainBlob absolute top-0 -right-80 w-[23rem] h-[23rem] rounded-full bg-[#FF4095] mix-blend-multiply filter blur-3xl  opacity-60 " ></div>
          <div className="animate-mainBlob absolute top-32 -right-40 w-[26rem] h-[26rem] rounded-full bg-[#6f87fc] mix-blend-overlay filter blur-3xl  opacity-60 " ></div>
          <div className="animate-mainBlob absolute top-72 -right-72 w-[24rem] h-[24rem] rounded-full bg-[#00FFFF] mix-blend-multiply filter blur-3xl  opacity-60 " ></div>
        </div>

        {/* <h2 className=" mt-40 animate-text bg-gradient-to-r from-teal-500 via-purple-500 to-orange-500 bg-clip-text text-transparent text-5xl font-black" >Noru_ </h2> */}
        <div class="flex mt-12 space-x-20 items-center justify-between">
          <div className="flex flex-col  basis-[40%] space-y-12 " >
            <div className="flex mt-20 -mb-3 -space-x-0 items-end justify-start" >
              <h2 className="font-space animate-text bg-gradient-to-r from-teal-500 via-purple-500 to-orange-500 bg-clip-text text-transparent text-5xl font-black" >Noru_ </h2>
              <p class=" rounded-2xl px-3 py-0 bg-purple-300 font-semibold text-base">yasier</p>
            </div>
            <p class="mt-12 font-base font-jak  text-[1.08rem] ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur fugiat provident labore maxime dignissimos, unde rem quae natus neque quisquam quaerat optio ipsam! Dignissimos consectetur doloremque nostrum. Doloremque, molestias cupiditate.</p>
          </div>
          <div className=" basis-[50%] " >
            <Image src={'/main.png'} width={600} height={400} alt={'main image'} />
          </div>
        </div>

      </main>
    </div>
  )
}
