import Head from 'next/head';
import WorkCard from '../components/WorkCard';
export default function Work() {
    return (
        <div className="px-10 sm:px-20 md:px-32 md:-mb-52 lg:mb-0 lg:px-60 mx-auto">
            <Head>
                <title>noru ✨ web dev ✨ student </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen max-w-screen ">
                <div className="pt-24 flex flex-col items-center mx-auto">
                    <h2
                        className={` font-play italic bg-gradient-to-r from-[#4ce3e1] via-[#be45ff] to-[#ff8a2a] bg-clip-text text-transparent items-center mx-auto text-2xl md:text-3xl lg:text-4xl xl:text-5xl font-black`}
                    >
                        Works
                    </h2>
                    <p className="mt-8 text-sm md:text-md lg:text-lg xl:text-xl">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, et. Placeat
                        quam quod blanditiis, dignissimos praesentium a provident ipsa. Quo officiis
                        perspiciatis soluta, possimus quidem esse quia assumenda voluptate
                        veritatis!
                    </p>
                </div>
                <div className="mt-20 flex flex-col space-y-4 sm:space-y-6 md:space-y-8 lg:space-y-12 mx-auto items-center w-full md:w-[80%] lg:w-[75%]">
                    <WorkCard
                        title={'nKrypt'}
                        description={'lorem ipsum dorem dolor sit amet consec tetur elit.'}
                        arr={[null, 1, null, 1, null, 1, null, 1]}
                        img={'/pfpimg.jpeg'}
                    />
                    <WorkCard
                        title={'nKrypt'}
                        description={'lorem ipsum dorem dolor sit amet consec tetur elit.'}
                        arr={[1, null, 1, null, null, 1, null, 1]}
                        img={'/pfpimg.jpeg'}
                    />
                    <WorkCard
                        title={'nKrypt'}
                        description={'lorem ipsum dorem dolor sit amet consec tetur elit.'}
                        arr={[1, null, null, 1, 1, null, 1]}
                        img={'/pfpimg.jpeg'}
                    />
                </div>
            </main>
        </div>
    );
}
