import Head from "next/head"
import Image from "next/image"
import { IoLogoReact } from 'react-icons/io5'
import { SiTypescript, SiNextdotjs, SiJavascript, SiTailwindcss, SiMongodb, SiSolidity } from 'react-icons/si'

export default function Work() {
    return (
        <div className="px-60 mx-auto" >
            <Head>
                <title>noru ✨ web dev ✨ student </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="" >
                <div className="my-20 flex flex-col space-y-12 mx-auto items-center w-[75%]" >
                    <div className="flex h-40 bg-gray-400 overflow-hidden rounded-3xl  ">
                        <div class="relative basis-[45%] rounded-3xl overflow-hidden ">
                            {/* <div className="absolute right-20 -z-10" >
                                <div className="animate-mainBlob mb-1 absolute top-0 -right-28 w-32 h-32 rounded-full bg-[#FF4095] mix-blend-multiply filter blur-xl opacity-60 " ></div>
                                <div className="animate-mainBlob mb-2 absolute top-12 -right-10 w-32 h-32 rounded-full bg-[#6f87fc] mix-blend-overlay filter blur-xl opacity-60 " ></div>
                                <div className="animate-mainBlob mb-3 absolute top-12 -right-20 w-32 h-32 rounded-full bg-[#00FFFF] mix-blend-multiply filter blur-xl opacity-60 " ></div>
                            </div> */}
                            {/* <div className="w-inherit  h-inherit" >
                            </div> */}
                            <Image src='/pfpimg.jpeg' layout="fill" alt="work-1" className="object-cover rounded-3xl hover:scale-[1.2] transition-all duration-700 ease-linear " />
                        </div>
                        <div className="grid grid-cols gap-y-4 px-8 py-4 basis-[70%]" >
                            <div className="flex justify-between items-center" >
                                <div className="font-space font-black text-xl " >nKrypt</div>
                                <div className="flex flex-row space-x-2 justify-between" >
                                    <SiJavascript className="h-4 w-4" />
                                    <SiTypescript className="h-4 w-4" />
                                    <IoLogoReact className="h-4 w-4" />
                                    <SiNextdotjs className="h-4 w-4" />
                                    <SiTailwindcss className="h-4 w-4" />
                                    <SiMongodb className="h-4 w-4" />
                                    <SiSolidity className="h-4 w-4" />

                                </div>
                            </div>
                            <div className="font-semibold text-[0.9rem]" >
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus voluptate fugit placeat
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit

                            </div>
                        </div>
                    </div>
                    <div className="flex h-40 bg-gray-400 overflow-hidden rounded-3xl  ">
                        <div class="relative basis-[45%] rounded-3xl overflow-hidden ">
                            <Image src='/pfpimg.jpeg' layout="fill" alt="work-1" className="object-cover rounded-3xl hover:scale-[1.2] transition-all duration-700 ease-linear " />
                        </div>
                        <div className="grid grid-cols gap-y-4 px-8 py-4 basis-[70%]" >
                            <div className="flex justify-between items-center" >
                                <div className="font-space font-black text-xl " >nKrypt</div>
                                <div className="flex flex-row space-x-2 justify-between" >
                                    <SiJavascript className="h-4 w-4" />
                                    <SiTypescript className="h-4 w-4" />
                                    <IoLogoReact className="h-4 w-4" />
                                    <SiNextdotjs className="h-4 w-4" />
                                    <SiTailwindcss className="h-4 w-4" />
                                    <SiMongodb className="h-4 w-4" />
                                    <SiSolidity className="h-4 w-4" />

                                </div>
                            </div>
                            <div className="font-semibold text-[0.9rem]" >
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus voluptate fugit placeat
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit

                            </div>
                        </div>
                    </div>
                    <div className="flex h-40 bg-gray-400 overflow-hidden rounded-3xl  ">
                        <div class="relative basis-[45%] rounded-3xl overflow-hidden ">
                            <Image src='/pfpimg.jpeg' layout="fill" alt="work-1" className="object-cover rounded-3xl hover:scale-[1.2] transition-all duration-700 ease-linear " />
                        </div>
                        <div className="grid grid-cols gap-y-4 px-8 py-4 basis-[70%]" >
                            <div className="flex justify-between items-center" >
                                <div className="font-space font-black text-xl " >nKrypt</div>
                                <div className="flex flex-row space-x-2 justify-between" >
                                    <SiJavascript className="h-4 w-4" />
                                    <SiTypescript className="h-4 w-4" />
                                    <IoLogoReact className="h-4 w-4" />
                                    <SiNextdotjs className="h-4 w-4" />
                                    <SiTailwindcss className="h-4 w-4" />
                                    <SiMongodb className="h-4 w-4" />
                                    <SiSolidity className="h-4 w-4" />

                                </div>
                            </div>
                            <div className="font-semibold text-[0.9rem]" >
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus voluptate fugit placeat
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit

                            </div>
                        </div>
                    </div>
                </div>

            </main>
        </div>
    )
}